// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clipboard_inspect_windows
Rcpp::DataFrame clipboard_inspect_windows();
RcppExport SEXP _yclip_clipboard_inspect_windows() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(clipboard_inspect_windows());
    return rcpp_result_gen;
END_RCPP
}
// clipboard_isolate_windows
void clipboard_isolate_windows(Rcpp::List formats);
RcppExport SEXP _yclip_clipboard_isolate_windows(SEXP formatsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type formats(formatsSEXP);
    clipboard_isolate_windows(formats);
    return R_NilValue;
END_RCPP
}
// clipboard_read_raw_windows
Rcpp::RawVector clipboard_read_raw_windows(SEXP format_input);
RcppExport SEXP _yclip_clipboard_read_raw_windows(SEXP format_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type format_input(format_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(clipboard_read_raw_windows(format_input));
    return rcpp_result_gen;
END_RCPP
}
// clipboard_write_formats_windows
void clipboard_write_formats_windows(Rcpp::List data);
RcppExport SEXP _yclip_clipboard_write_formats_windows(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    clipboard_write_formats_windows(data);
    return R_NilValue;
END_RCPP
}
// clipboard_read_unicode_text_windows
std::string clipboard_read_unicode_text_windows();
RcppExport SEXP _yclip_clipboard_read_unicode_text_windows() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(clipboard_read_unicode_text_windows());
    return rcpp_result_gen;
END_RCPP
}
// clipboard_read_dib_windows
Rcpp::RawVector clipboard_read_dib_windows();
RcppExport SEXP _yclip_clipboard_read_dib_windows() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(clipboard_read_dib_windows());
    return rcpp_result_gen;
END_RCPP
}
// clipboard_inspect_dib_windows
Rcpp::List clipboard_inspect_dib_windows();
RcppExport SEXP _yclip_clipboard_inspect_dib_windows() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(clipboard_inspect_dib_windows());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_yclip_clipboard_inspect_windows", (DL_FUNC) &_yclip_clipboard_inspect_windows, 0},
    {"_yclip_clipboard_isolate_windows", (DL_FUNC) &_yclip_clipboard_isolate_windows, 1},
    {"_yclip_clipboard_read_raw_windows", (DL_FUNC) &_yclip_clipboard_read_raw_windows, 1},
    {"_yclip_clipboard_write_formats_windows", (DL_FUNC) &_yclip_clipboard_write_formats_windows, 1},
    {"_yclip_clipboard_read_unicode_text_windows", (DL_FUNC) &_yclip_clipboard_read_unicode_text_windows, 0},
    {"_yclip_clipboard_read_dib_windows", (DL_FUNC) &_yclip_clipboard_read_dib_windows, 0},
    {"_yclip_clipboard_inspect_dib_windows", (DL_FUNC) &_yclip_clipboard_inspect_dib_windows, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_yclip(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
