
#' Format a named list of knitr chunk options as header text
#' @noRd
format_chunk_options <- function(options) {
  if (length(options) == 0L) return(character())
  purrr::imap_chr(options, \(val, nm) {
    val <- dplyr::case_when(
      is.character(val) ~ stringr::str_c("'", val, "'"),
      is.logical(val) ~ if (isTRUE(val)) "TRUE" else "FALSE",
      TRUE ~ as.character(val)
    )
    stringr::str_c(nm, "=", val)
  })
}


#' Inject a background color into the pre.sourceCode CSS rule
#' @noRd
apply_sourcecode_background <- function(html, background = NULL) {
  if (is.null(background)) return(html)
  stringr::str_replace(
    html,
    stringr::regex("(pre\\.sourceCode\\s*\\{[^}]*)(\\})"),
    stringr::str_c("\\1 background-color: ", background, ";\\2")
  )
}


#' Convert R Code to Formatted HTML
#'
#' @param code
#' @param options
#'
#' @return
#' @export
#'
#' @examples
knit_code_OLD <- function(code, options = list()) {
  workdir <- tempfile()
  dir.create(workdir)
  on.exit(unlink(workdir, recursive = TRUE), add = TRUE)
  old_opts <- knitr::opts_chunk$get()
  on.exit(knitr::opts_chunk$set(old_opts), add = TRUE)
  figdir <- file.path(workdir, "figure")
  dir.create(figdir)
  knitr::opts_chunk$set(
    comment = "#>",
    echo = TRUE,
    fig.path = paste0(figdir, "/")
  )
  if (length(options) > 0L) {
    knitr::opts_chunk$set(options)
  }
  text <- c("```{r}", code, "```")
  md <- file.path(workdir, "output.md")
  knitr::knit(
    text = text,
    output = md,
    envir = globalenv()
  )
  md_text <- readLines(md)
  md_text <- stringr::str_replace_all(
    md_text,
    stringr::fixed(workdir),
    "."
  )
  writeLines(md_text, md)
  pandoc <- find_pandoc()
  html <- file.path(workdir, "output.html")
  system2(
    pandoc,
    c(
      "-f", "markdown",
      "-t", "html",
      "--standalone",
      "--embed-resources",
      "--resource-path", dirname(md),
      "-o", html,
      md
    )
  )
  readr::read_file(html)
}





#' Apply syntax highlighting to source code using Pandoc
#'
#' Converts source code to syntax-highlighted HTML using Pandoc's
#' syntax-highlighting engine. The resulting HTML contains the CSS
#' generated by Pandoc and the highlighted code block, making it suitable
#' for writing to the Windows clipboard as an HTML clipboard format.
#'
#' @param text_code A single character string containing the source code
#'   to be highlighted.
#' @param language A single character string specifying the programming
#'   language of `text_code`, using a language identifier recognized by
#'   Pandoc.
#' @param style A single character string specifying the Pandoc syntax
#'   highlighting style. Defaults to `"pygments"`. Other styles supported
#'   by the installed version of Pandoc can be supplied.
#'   Run `system2(find_pandoc(), "--list-highlight-styles", stdout = TRUE)`
#'   to list available styles.
#' @param background A single character string specifying the CSS
#'   background color for the highlighted code block. Defaults to
#'   `"#eeeeee"`. If `NULL`, no background color is added.
#' @param additional_args A character vector of additional command-line
#'   arguments passed directly to Pandoc. This provides an escape hatch
#'   for Pandoc options not directly exposed by this function. For example,
#'   `c("-V monofont=Consolas")` can be used to specify the monospace
#'   font.
#'
#' @return A character string containing HTML with the Pandoc-generated
#'   CSS and syntax-highlighted code block.
#'
#' @examples
#' code <- paste(
#'   "x <- 1:10",
#'   "mean(x)",
#'   sep = "\n"
#' )
#'
#' html <- syntax_highlighting(
#'   code,
#'   language = "r"
#' )
#'
#' html2 <- syntax_highlighting(
#'   code,
#'   language = "r",
#'   style = "breezeDark",
#'   additional_args = "-V fontsize=21pt"
#' )
#' @export
syntax_highlighting_OLD <- function(
    text_code,
    language,
    style = "pygments",
    background = "#eeeeee",
    additional_args = character()
) {
  if (!is.character(text_code) || length(text_code) != 1L || is.na(text_code)) {
    cli::cli_abort("`text_code` must be a single non-missing character string.")
  }
  if (!is.character(language) || length(language) != 1L || is.na(language)) {
    cli::cli_abort("`language` must be a single non-missing character string.")
  }
  if (!nzchar(language)) {
    cli::cli_abort("`language` must not be empty.")
  }
  if (!is.character(style) || length(style) != 1L || is.na(style)) {
    cli::cli_abort("`style` must be a single non-missing character string.")
  }
  if (!is.null(background)) {
    if (!is.character(background) || length(background) != 1L || is.na(background)) {
      cli::cli_abort("`background` must be `NULL` or a single non-missing character string.")
    }
    if (!nzchar(background)) {
      cli::cli_abort("`background` must not be empty.")
    }
  }
  if (!is.character(additional_args) || anyNA(additional_args)) {
    cli::cli_abort("`additional_args` must be a character vector with no missing values.")
  }
  pandoc <- find_pandoc()
  markdown <- paste0(
    "```{.", language, "}\n",
    text_code,
    "\n```\n"
  )
  args <- c(
    "-f markdown",
    "-t html",
    "--standalone",
    "--metadata", "title=Code",
    paste0("--highlight-style=", style),
    additional_args
  )
  result <- system2(
    pandoc,
    args,
    input = markdown,
    stdout = TRUE
  )
  html <- paste(result, collapse = "\n")
  if (!is.null(background)) {
    # CHANGE: pre.sourceCode { margin: 0; }
    # TO:     pre.sourceCode { margin: 0;  background-color: #eeeeee;}
    html <- stringr::str_replace(
      html,
      "(pre\\.sourceCode\\s*\\{[^}]*)(\\})",
      paste0("\\1 background-color: ",background,";\\2")
    )
  }
  style_block <- stringr::str_extract(html,"(?s)<style[^>]*>.*?</style>")
  code_block <- stringr::str_extract(html,"(?s)<div class=\"sourceCode\".*?</div>")
  if (is.na(style_block) || is.na(code_block)) {
    cli::cli_abort("Pandoc did not produce the expected syntax-highlighted HTML.")
  }
  paste0(style_block, "\n", code_block)
}

