# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Inspect Clipboard on Windows
#'
#' @return data frame showing the various formats available on the clipboard
#' @export
clipboard_inspect_windows <- function() {
    .Call(`_yclip_clipboard_inspect_windows`)
}

clipboard_isolate_windows <- function(formats) {
    invisible(.Call(`_yclip_clipboard_isolate_windows`, formats))
}

clipboard_read_raw_windows <- function(format_input) {
    .Call(`_yclip_clipboard_read_raw_windows`, format_input)
}

clipboard_write_formats_windows <- function(data) {
    invisible(.Call(`_yclip_clipboard_write_formats_windows`, data))
}

clipboard_read_unicode_text_windows <- function() {
    .Call(`_yclip_clipboard_read_unicode_text_windows`)
}

clipboard_read_dib_windows <- function() {
    .Call(`_yclip_clipboard_read_dib_windows`)
}

clipboard_inspect_dib_windows <- function() {
    .Call(`_yclip_clipboard_inspect_dib_windows`)
}

