# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clipboard_inspect_windows <- function() {
    .Call(`_yclip_clipboard_inspect_windows`)
}

clipboard_read_raw_windows <- function(format_name) {
    .Call(`_yclip_clipboard_read_raw_windows`, format_name)
}

